version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SURREALDB_URL=http://surrealdb:8000
      - SURREALDB_NAMESPACE=test
      - SURREALDB_DATABASE=test
      - SURREALDB_USER=root
      - SURREALDB_PASSWORD=root
      - SURREAL_ADDRESS=http://surrealdb:8000
      - SURREAL_NAMESPACE=test
      - SURREAL_DB=test
      - SURREAL_USER=root
      - SURREAL_PASS=root
    depends_on:
      - surrealdb
    volumes:
      - .:/app
      - ./surreal-lite-py:/app/surreal-lite-py
      - ./podcastfy:/app/podcastfy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/var/lib/surrealdb
    command: start --log trace --user root --pass root file:///var/lib/surrealdb/data
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  surreal_data:
    driver: local
